(function($){
  $(function(){

    $('.button-collapse').sideNav();
    $('.parallax').parallax();
    $('.modal-trigger').leanModal();
    $('select').material_select();
    $('#programsMenu').click(function(){
        event.preventDefault();
        $('#CrossFitPage').addClass('hide');
        $('#MMAPage').addClass('hide');
        $('#KidsMMAPage').addClass('hide');
        $('#PersonalTrainingPage').addClass('hide');
        $('#ContactUsPage').addClass('hide');
        $('#PricingPage').addClass('hide');
        $('#BlogsPage').addClass('hide');
    });
    $('#pricingMenu').click(function(){
        event.preventDefault();
        $('#CrossFitPage').addClass('hide');
        $('#MMAPage').addClass('hide');
        $('#KidsMMAPage').addClass('hide');
        $('#PersonalTrainingPage').addClass('hide');
        $('#ContactUsPage').addClass('hide');
        $('#PricingPage').removeClass('hide');
        $('#BlogsPage').addClass('hide');
    });
    $('#personalMenu').click(function(){
        event.preventDefault();
        $('#CrossFitPage').addClass('hide');
        $('#MMAPage').addClass('hide');
        $('#KidsMMAPage').addClass('hide');
        $('#PersonalTrainingPage').removeClass('hide');
        $('#ContactUsPage').addClass('hide');
        $('#PricingPage').addClass('hide');
        $('#BlogsPage').addClass('hide');
    });
    $('#contactMenu').click(function(){
        event.preventDefault();
        $('#CrossFitPage').addClass('hide');
        $('#MMAPage').addClass('hide');
        $('#KidsMMAPage').addClass('hide');
        $('#PersonalTrainingPage').addClass('hide');
        $('#ContactUsPage').removeClass('hide');
        $('#PricingPage').addClass('hide');
        $('#BlogsPage').addClass('hide');
    });
    $('#blogMenu').click(function(){
        event.preventDefault();
        $('#CrossFitPage').addClass('hide');
        $('#MMAPage').addClass('hide');
        $('#KidsMMAPage').addClass('hide');
        $('#PersonalTrainingPage').addClass('hide');
        $('#ContactUsPage').addClass('hide');
        $('#PricingPage').addClass('hide');
        $('#BlogsPage').removeClass('hide');
    });
    $('#crossFitButton').click(function(){
        event.preventDefault();
        $('#CrossFitPage').removeClass('hide');
        $('#MMAPage').addClass('hide');
        $('#KidsMMAPage').addClass('hide');
        $('#PersonalTrainingPage').addClass('hide');
        $('#ContactUsPage').removeClass('hide');
        $('#PricingPage').addClass('hide');
        $('#BlogsPage').addClass('hide');
    });
    $('#mmaButton').click(function(){
        event.preventDefault();
        $('#CrossFitPage').addClass('hide');
        $('#MMAPage').removeClass('hide');
        $('#KidsMMAPage').addClass('hide');
        $('#PersonalTrainingPage').addClass('hide');
        $('#ContactUsPage').removeClass('hide');
        $('#PricingPage').addClass('hide');
        $('#BlogsPage').addClass('hide');
    });
    $('#personalButton').click(function(){
        event.preventDefault();
        $('#CrossFitPage').addClass('hide');
        $('#MMAPage').addClass('hide');
        $('#KidsMMAPage').addClass('hide');
        $('#PersonalTrainingPage').removeClass('hide');
        $('#ContactUsPage').removeClass('hide');
        $('#PricingPage').addClass('hide');
        $('#BlogsPage').addClass('hide');
    });
    $('#kidsButton').click(function(){
        event.preventDefault();
        $('#CrossFitPage').addClass('hide');
        $('#MMAPage').addClass('hide');
        $('#KidsMMAPage').removeClass('hide');
        $('#PersonalTrainingPage').addClass('hide');
        $('#ContactUsPage').removeClass('hide');
        $('#PricingPage').addClass('hide');
        $('#BlogsPage').addClass('hide');
    });
  }); // end of document ready
})(jQuery); // end of jQuery name space